name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: stayn1ght/mycgutdb_document@master
        env:
          ACCESS_TOKEN: ${{ secrets.gmdb114514 }}
          TARGET_REPO: stayn1ght/mycgutdb_document
          TARGET_BRANCH: master
          BUILD_SCRIPT: pnpm && pnpm docs:build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: https://mycgutdb.document.com
